### ISSUE TITLE
No Files?

### ISSUE THREAD

**Issue by Thundros** [rubenandrebarreiro/3d-object-viewer-super-mario-bros#1]
Hi, when I try to download the zip file, I only get a readme.md. Please upload files.

**Comment by Thundros** [comment]
Hello?...

**Comment by rubenandrebarreiro** [comment]
Hello, 
Sorry for the late response...

I've being a little busy with other projects in my college... I'll upload the project soon, it's not finished yet...

You have a little demo here, but it's incomplete...
https://rubenandrebarreiro.github.io/projects/threejs/3d-object-super-mario-bros/3d-object-super-mario-bros.html

Thank you very much!

**Comment by rubenandrebarreiro** [comment]
> Hi, when I try to download the zip file, I only get a readme.md. Please upload files.

Hi @Thundros, I will upload the files very soon. I just got time now to work more on this, because of the semester on college. Stay tuned! 💪

**Comment by rubenandrebarreiro** [comment]
Hello @Thundros! It's already available a 1st version (almost complete, but NOT totally complete)!
